name: angular_app
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '>=2.10.4 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_components: ^1.0.3
  angular_router: ^2.0.0
  angular_forms: ^3.0.0
  i69n: ^1.1.0
  intl: ^0.16.0
  ng_bootstrap: ^1.2.0 
  crypto: ^2.1.5
  cryptoutils: ^0.5.0
  jiffy: ^3.0.1
  chartjs: ^0.6.0
  pdf: ^2.1.0
  excel: ^1.1.5
  darq: ^1.1.1

dev_dependencies:
  angular_test: ^3.0.0
  build_runner: ^1.5.1
  build_test: ^1.3.6
  build_web_compilers: ^2.1.0
  build_config: ^0.4.1
  sass_builder: ^2.0.0
  test: ^1.6.4
